### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by hahahahahahahahahahahahahahahah** [3xp10it/xwaf#21]
```
$ python3 xwaf.py
Requirement already up-to-date: exp10it in /data/data/com.termux/files/usr/lib/python3.8/site-packages (2.7.21)
Requirement already satisfied, skipping upgrade: mechanicalsoup in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (0.12.0)
Requirement already satisfied, skipping upgrade: bs4 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (0.0.1)
Requirement already satisfied, skipping upgrade: selenium in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (3.141.0)
Requirement already satisfied, skipping upgrade: colorama in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (0.4.1)
Requirement already satisfied, skipping upgrade: requests in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (2.22.0)
Requirement already satisfied, skipping upgrade: configparser in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (4.0.2)
Requirement already satisfied, skipping upgrade: chardet in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (3.0.4)
Requirement already satisfied, skipping upgrade: wget in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (3.2)
Requirement already satisfied, skipping upgrade: pycrypto in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (2.6.1)
Requirement already satisfied, skipping upgrade: pymysql in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from exp10it) (0.9.3)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.4 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from mechanicalsoup->exp10it) (4.8.1)
Requirement already satisfied, skipping upgrade: lxml in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from mechanicalsoup->exp10it) (4.4.2)
Requirement already satisfied, skipping upgrade: six>=1.4 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from mechanicalsoup->exp10it) (1.13.0)
Requirement already satisfied, skipping upgrade: urllib3 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from selenium->exp10it) (1.25.7)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests->exp10it) (2.6)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from requests->exp10it) (2017.7.27.1)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in /data/data/com.termux/files/usr/lib/python3.8/site-packages (from beautifulsoup4>=4.4->mechanicalsoup->exp10it) (1.9.5)
fatal: could not create leading directories of '/usr/share/sqlmap': Read-only file system
/tmp/xwaf.py: No such file or directory
Traceback (most recent call last):
  File "xwaf.py", line 2843, in <module>
    Program()
  File "xwaf.py", line 33, in __init__
    self.selfUpdate()
  File "xwaf.py", line 178, in selfUpdate
    latestVersion=getVersion("/tmp/xwaf.py")
  File "xwaf.py", line 171, in getVersion
    with open("/tmp/xwaf.py","r+") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/xwaf.py'
$
```
```
$ uname -a
Linux localhost 4.9.112-perf-g495fd4d #1 SMP PREEMPT Sat Jan 11 23:56:03 CST 2020 aarch64 Android
```

**Comment by hahahahahahahahahahahahahahahah** [comment]
手機: redmi 8 miui 11 android 9
app: https://github.com/termux
https://play.google.com/store/apps/details?id=com.termux

**Comment by hahahahahahahahahahahahahahahah** [comment]
我改了路徑 但这个不知道咋改
```
[正在执行:python2 /usr/share/sqlmap/sqlmap.py -v "2" --null-connection --dbms "mysql" --technique "E" --parse-errors -u "https://ido.vtc.edu.hk/textonly/tc/news_detail/149*/" --level "5" --risk "1" --delay "0.1" --time-sec "15" --unstable --random-agent --drop-set-cookie  --dbs --batch --threads "4" --safe-url "https://ido.vtc.edu.hk" --safe-freq "1" --smart --no-cast --tamper "varnish,xforwardedfor,multiplespaces,rapython2: can't open file '/usr/share/sqlmap/sqlmap.py': [Errno 2] No such file or directory
```
对应位置：`/data/data/com.termux/files/usr/share/sqlmap/sqlmap.py`
