### ISSUE TITLE
figlet error

### ISSUE THREAD

**Issue by 5l1v3r1** [3xp10it/xwaf#23]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/exp10it.py", line 1465, in figlet2file
    figlet_font_dir = all[0][:-1]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "xcdn.py", line 22, in <module>
    figlet2file("3xp10it",0,True)
  File "/usr/local/lib/python3.7/dist-packages/exp10it.py", line 1472, in figlet2file
    figlet_font_dir = all[0][:-1]
IndexError: list index out of range

**Comment by 3xp10it** [comment]
试试新版本,应该解决了这个问题.
