### ISSUE TITLE
请问一下，这个怎么解决

### ISSUE THREAD

**Issue by 158668** [3xp10it/xwaf#27]
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from mechanicalsoup->exp10it) (4.6.1)
Traceback (most recent call last):
  File "xwaf.py", line 2846, in <module>
    Program()
  File "xwaf.py", line 33, in __init__
    self.selfUpdate()
  File "xwaf.py", line 181, in selfUpdate
    latestVersion=getVersion("/tmp/xwaf.py")
  File "xwaf.py", line 176, in getVersion
    latestVersion=re.search(r"self\.currentVersion\s*=\s*(.*)",content).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by 3xp10it** [comment]
可以试下把181行注释掉再运行，应该可行。
`#selfUpdate`
